# Generated by Django 3.0.5 on 2020-04-14 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_auto_20200414_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'специальность', 'verbose_name_plural': 'специальности'},
        ),
    ]
