# Generated by Django 3.0.5 on 2020-04-18 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0012_auto_20200418_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='vacancies.Company'),
        ),
    ]
