# Generated by Django 3.0.5 on 2020-04-18 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0014_companyowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='owner',
        ),
    ]
