# Generated by Django 3.0.5 on 2020-04-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0015_remove_vacancy_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employee_count',
            field=models.TextField(),
        ),
    ]
