# Generated by Django 3.0.5 on 2020-04-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0016_auto_20200419_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='60x60.png', null=True, upload_to='MEDIA_COMPANY_IMAGE_DIR'),
        ),
    ]
